/**
 * Site-wide social link-preview card (Open Graph + Twitter), generated by next/og.
 * Renders the Night Garage brand card so a pasted heliquant.vercel.app link shows a real
 * preview on WhatsApp / Telegram / X / Discord / IG. No design tool, no external asset — pure
 * JSX/CSS via satori. 1200×630 (the social standard).
 */
import { ImageResponse } from "next/og";

export const alt = "HeliQuant — The disciplined trading engine";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#0b0b0b",
          padding: "56px 64px",
          fontFamily: "sans-serif",
          color: "#f2efe6",
        }}
      >
        {/* hazard seam */}
        <div
          style={{
            display: "flex",
            height: 16,
            width: "100%",
            backgroundImage:
              "repeating-linear-gradient(45deg, #c9f24b 0px, #c9f24b 20px, #0b0b0b 20px, #0b0b0b 40px)",
          }}
        />

        {/* brand block */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", fontSize: 24, letterSpacing: 6, color: "#8b8b80" }}>
            AUTONOMOUS MULTI-DESK AI TRADING FIRM / MANTLE
          </div>
          <div style={{ display: "flex", fontSize: 150, fontWeight: 800, marginTop: 8, lineHeight: 1 }}>
            <span style={{ color: "#f2efe6" }}>HELI</span>
            <span style={{ color: "#c9f24b" }}>QUANT</span>
          </div>
          <div style={{ display: "flex", fontSize: 44, color: "#f2efe6", marginTop: 14 }}>
            The disciplined trading engine
          </div>
          <div style={{ display: "flex", fontSize: 26, color: "#8b8b80", marginTop: 10 }}>
            9 desks / holds gear until a validated edge / every decision sealed on-chain
          </div>
        </div>

        {/* footer: the honesty line + url */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
          <div
            style={{
              display: "flex",
              fontSize: 30,
              fontWeight: 700,
              letterSpacing: 2,
              color: "#c9f24b",
            }}
          >
            WE PUBLISH WHAT DOESN&apos;T WORK
          </div>
          <div style={{ display: "flex", fontSize: 24, color: "#8b8b80" }}>heliquant.vercel.app</div>
        </div>
      </div>
    ),
    { ...size },
  );
}
