/**
 * Site-wide social link-preview card (Open Graph + Twitter), generated by next/og.
 * Night Garage brand card — Saira Extra Condensed (same display face as the hero), hazard seam,
 * meshed gears, chartreuse accent on pitch. 1200×630. Pure JSX/CSS via satori; the headline font is
 * the bundled Saira ExtraCondensed TTF (satori can't read the woff2 next/font serves).
 */
import { readFileSync } from "fs";
import { join } from "path";

import { ImageResponse } from "next/og";

export const runtime = "nodejs"; // so we can read the bundled TTF off disk at generation time
export const alt = "HeliQuant — The disciplined trading engine";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function OpengraphImage() {
  let fonts;
  try {
    const data = readFileSync(join(process.cwd(), "src/app/SairaExtraCondensed-ExtraBold.ttf"));
    fonts = [{ name: "Saira", data, weight: 800 as const, style: "normal" as const }];
  } catch {
    fonts = undefined; // fall back to the system font if the bundled face can't be read
  }

  // the full HeliQuant logo (rotor + eagle), bg removed. It's black+chartreuse so on the pitch backdrop
  // it gets a bone "sticker" plate (garage livery) — the black reads, the chartreuse pops.
  let logoUri = "";
  try {
    const png = readFileSync(join(process.cwd(), "public/brand/logo-full.png")).toString("base64");
    logoUri = `data:image/png;base64,${png}`;
  } catch {
    logoUri = "";
  }

  return new ImageResponse(
    (
      <div
        style={{
          position: "relative",
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#0b0b0b",
          padding: "56px 64px",
          fontFamily: fonts ? "Saira" : "sans-serif",
          color: "#f2efe6",
          overflow: "hidden",
        }}
      >
        {/* HeliQuant logo on a bone livery plate (right) */}
        {logoUri ? (
          <div
            style={{
              position: "absolute",
              right: 64,
              top: 150,
              display: "flex",
              padding: 26,
              background: "#f2efe6",
              borderRadius: 18,
            }}
          >
            <img src={logoUri} width={286} height={304} />
          </div>
        ) : null}

        {/* hazard seam */}
        <div
          style={{
            display: "flex",
            height: 16,
            width: "100%",
            backgroundImage:
              "repeating-linear-gradient(45deg, #c9f24b 0px, #c9f24b 20px, #0b0b0b 20px, #0b0b0b 40px)",
          }}
        />

        {/* brand block */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", fontSize: 26, letterSpacing: 8, color: "#8b8b80" }}>
            AUTONOMOUS MULTI-DESK AI TRADING FIRM / MANTLE
          </div>
          <div style={{ display: "flex", fontSize: 188, fontWeight: 800, marginTop: 4, lineHeight: 1 }}>
            <span style={{ color: "#f2efe6" }}>HELI</span>
            <span style={{ color: "#c9f24b" }}>QUANT</span>
          </div>
          <div style={{ display: "flex", fontSize: 52, color: "#f2efe6", marginTop: 10 }}>
            The disciplined trading engine
          </div>
          <div style={{ display: "flex", fontSize: 28, color: "#8b8b80", marginTop: 8, letterSpacing: 1 }}>
            9 desks / holds gear until a validated edge / every decision sealed on-chain
          </div>
        </div>

        {/* footer: the honesty line + url */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
          <div style={{ display: "flex", fontSize: 34, letterSpacing: 3, color: "#c9f24b" }}>
            WE PUBLISH WHAT DOESN&apos;T WORK
          </div>
          <div style={{ display: "flex", fontSize: 26, color: "#8b8b80", letterSpacing: 1 }}>
            heliquant.vercel.app
          </div>
        </div>
      </div>
    ),
    { ...size, ...(fonts ? { fonts } : {}) },
  );
}
